### ISSUE TITLE
ios 编译找不到这个文件啊

### ISSUE THREAD

**Issue by hjc22** [taijuan/image_picker_flutter#1]
/Users/hjc1/.pub-cache/hosted/pub.flutter-io.cn/image_picker_flutter-1.3.1/ios/Classes/ImagePickerFlutterPlugin.m:2:9: fatal error: 'image_picker_flutter/image_picker_flutter-Swift.h' file not found
    #import <image_picker_flutter/image_picker_flutter-Swift.h>

**Comment by taijuan** [comment]
ios编译需要先使用pod install生成编译环境

**Comment by hjc22** [comment]
弄好了  因为是swift编写的，所以搞了下swift的环境
